- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Mostrar versi칩n de Ansible empleada
      debug:
        var: ansible_version
    - name: Imprimir el sistema operativo
      debug:
        msg: "El sistema operativo de la m치quina es {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
    - name: Alpine
      block:
        - name: Obtener versi칩n de Python Alpine
          ansible.builtin.shell: "python3 --version"
          register: alpine_python_version
        - name: Mostrar datos
          debug:
            var: alpine_python_version
        - name: Guardar datos
          shell: 'echo "$AWX_PRIVATE_DATA_DIR,$PWD,{{ inventory_hostname }},{{alpine_python_version.stdout}}" >> /tmp/resultdata.csv'
          delegate_to: localhost
      when: ansible_facts['distribution'] == "Alpine"
    - name: Ubuntu
      block:
        - name: Obtener versi칩n de Python Ubuntu
          ansible.builtin.shell: "python3 --version"
          register: ubuntu_python_version
        - name: Mostrar datos
          debug:
            var: ubuntu_python_version
        - name: Guardar datos
          shell: 'echo "$AWX_PRIVATE_DATA_DIR,$PWD,{{ inventory_hostname }},{{ubuntu_python_version.stdout}}" >> /tmp/resultdata.csv'
          delegate_to: localhost
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: print magic vars
      debug:
        var: vars
    
