- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Imprimir el sistema operativo
      debug:
        msg: "El sistema operativo de la máquina es {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
    - name: Obtener versión de Python Alpine
      ansible.builtin.shell: "python3 --version"
      register: python_version
      when: ansible_facts['distribution'] == "Alpine"
    - name: Obtener versión de Python Ubuntu
      ansible.builtin.shell: "python3 --version"
      register: python_version
      when: ansible_facts['distribution'] == "Alpine"
    - name: Guardar datos
      shell: 'echo "{{ inventory_hostname }},{{python_version.stdout}}" >> /tmp/resultdata.csv'
      delegate_to: localhost
